/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as HealthMetricRouteImport } from './routes/health-metric'
import { Route as HealthRiskRouteImport } from './routes/health-risk'
import { Route as PopulationRouteImport } from './routes/population'
import { Route as RiskMapRouteImport } from './routes/risk-map'
import { Route as ThermalStressRouteImport } from './routes/thermal-stress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthMetricRoute = HealthMetricRouteImport.update({
  id: '/health-metric',
  path: '/health-metric',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRiskRoute = HealthRiskRouteImport.update({
  id: '/health-risk',
  path: '/health-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationRoute = PopulationRouteImport.update({
  id: '/population',
  path: '/population',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskMapRoute = RiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ThermalStressRoute = ThermalStressRouteImport.update({
  id: '/thermal-stress',
  path: '/thermal-stress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/health-metric': typeof HealthMetricRoute
  '/health-risk': typeof HealthRiskRoute
  '/population': typeof PopulationRoute
  '/risk-map': typeof RiskMapRoute
  '/thermal-stress': typeof ThermalStressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/health-metric': typeof HealthMetricRoute
  '/health-risk': typeof HealthRiskRoute
  '/population': typeof PopulationRoute
  '/risk-map': typeof RiskMapRoute
  '/thermal-stress': typeof ThermalStressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/health-metric': typeof HealthMetricRoute
  '/health-risk': typeof HealthRiskRoute
  '/population': typeof PopulationRoute
  '/risk-map': typeof RiskMapRoute
  '/thermal-stress': typeof ThermalStressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/forecast'
    | '/health-metric'
    | '/health-risk'
    | '/population'
    | '/risk-map'
    | '/thermal-stress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/forecast'
    | '/health-metric'
    | '/health-risk'
    | '/population'
    | '/risk-map'
    | '/thermal-stress'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/forecast'
    | '/health-metric'
    | '/health-risk'
    | '/population'
    | '/risk-map'
    | '/thermal-stress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DashboardRoute: typeof DashboardRoute
  ForecastRoute: typeof ForecastRoute
  HealthMetricRoute: typeof HealthMetricRoute
  HealthRiskRoute: typeof HealthRiskRoute
  PopulationRoute: typeof PopulationRoute
  RiskMapRoute: typeof RiskMapRoute
  ThermalStressRoute: typeof ThermalStressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-metric': {
      id: '/health-metric'
      path: '/health-metric'
      fullPath: '/health-metric'
      preLoaderRoute: typeof HealthMetricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-risk': {
      id: '/health-risk'
      path: '/health-risk'
      fullPath: '/health-risk'
      preLoaderRoute: typeof HealthRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population': {
      id: '/population'
      path: '/population'
      fullPath: '/population'
      preLoaderRoute: typeof PopulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-map': {
      id: '/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof RiskMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thermal-stress': {
      id: '/thermal-stress'
      path: '/thermal-stress'
      fullPath: '/thermal-stress'
      preLoaderRoute: typeof ThermalStressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DashboardRoute: DashboardRoute,
  ForecastRoute: ForecastRoute,
  HealthMetricRoute: HealthMetricRoute,
  HealthRiskRoute: HealthRiskRoute,
  PopulationRoute: PopulationRoute,
  RiskMapRoute: RiskMapRoute,
  ThermalStressRoute: ThermalStressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
